In [1]:
pip install xlrd==1.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlrd==1.2.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 8.4 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-1.2.0

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel("faridpur_eto.xls")

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [4]:
df

     STATIONID  YEAR  MONTH  DAYPART  MAXOFETO  AVGOFETO
0        11505  1987      1        1      2.50      2.50
1        11505  1987      2        1      3.29      3.29
2        11505  1987      3        1      4.75      4.75
3        11505  1987      4        1      5.61      5.61
4        11505  1987      5        1      5.81      5.81
..         ...   ...    ...      ...       ...       ...
259      11505  2008      8        1      3.77      3.77
260      11505  2008      9        1      3.80      3.80
261      11505  2008     10        1      3.22      3.22
262      11505  2008     11        1      2.76      2.76
263      11505  2008     12        1      1.88      1.88

[264 rows x 6 columns]

In [5]:
df_max = df.loc[:,["YEAR","MONTH","MAXOFETO"]]
df_avg = df.loc[:,["YEAR","MONTH","AVGOFETO"]]

In [6]:
monthly_max = df_max.groupby("MONTH").mean()
monthly_avg = df_avg.groupby("MONTH").mean()

In [7]:
monthly_max.reset_index(inplace = True)

In [8]:
monthly_analysis = monthly_max.merge(monthly_avg, on = "MONTH", how = "inner")

In [9]:
monthly_analysis.drop(["YEAR_x","YEAR_y"],axis = 1, inplace = True)

In [10]:
import calendar
monthly_analysis['MONTH'] = monthly_analysis['MONTH'].apply(lambda x: calendar.month_abbr[x])

In [11]:
monthly_analysis.to_excel("faridpur_eto_monthly_analysis.xls")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  """Entry point for launching an IPython kernel.

In [12]:
monthly_analysis.nlargest(2,"MAXOFETO")

  MONTH  MAXOFETO  AVGOFETO
3   Apr  5.224545  5.224545
4   May  4.943636  4.943636

In [13]:
monthly_analysis.nlargest(2,"AVGOFETO")

  MONTH  MAXOFETO  AVGOFETO
3   Apr  5.224545  5.224545
4   May  4.943636  4.943636

In [14]:
monthly_analysis.nsmallest(2,"MAXOFETO")

   MONTH  MAXOFETO  AVGOFETO
11   Dec  2.139091  2.139091
0    Jan  2.181818  2.181818

In [15]:
monthly_analysis.nsmallest(2,"AVGOFETO")

   MONTH  MAXOFETO  AVGOFETO
11   Dec  2.139091  2.139091
0    Jan  2.181818  2.181818