In [1]:
pip install xlrd==1.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlrd==1.2.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 5.1 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-1.2.0

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel("Faridpur_evpaoration.xls")

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [4]:
df

     STATIONID  YEAR  MONTH  MAXOFTSVALUE_UPDATED  AVGOFTSVALUE_UPDATED
0           62  1987      5                  14.5                  6.92
1           62  1987      7                   8.7                  4.42
2           62  1987      8                   9.3                  5.15
3           62  1988      4                   9.9                  7.02
4           62  1990      1                   4.8                  2.49
..         ...   ...    ...                   ...                   ...
264         62  2007      1                   3.7                  1.22
265         62  2007      2                   2.9                  1.43
266         62  2008     12                   1.9                  0.86
267         62  2009     11                   2.8                  1.43
268         62  2010      2                   3.8                  1.65

[269 rows x 5 columns]

In [6]:
df_max = df.loc[:,["YEAR","MONTH","MAXOFTSVALUE_UPDATED"]]
df_avg = df.loc[:,["YEAR","MONTH","AVGOFTSVALUE_UPDATED"]]

In [7]:
monthly_max = df_max.groupby("MONTH").mean()
monthly_avg = df_avg.groupby("MONTH").mean()

In [10]:
monthly_max.reset_index(inplace = True)

In [12]:
monthly_analysis = monthly_max.merge(monthly_avg, on = "MONTH", how = "inner")

In [13]:
monthly_analysis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   MONTH                 12 non-null     int64
 1   YEAR_x                12 non-null     float64
 2   MAXOFTSVALUE_UPDATED  12 non-null     float64
 3   YEAR_y                12 non-null     float64
 4   AVGOFTSVALUE_UPDATED  12 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 576.0 bytes

In [14]:
monthly_analysis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   MONTH                 12 non-null     int64
 1   YEAR_x                12 non-null     float64
 2   MAXOFTSVALUE_UPDATED  12 non-null     float64
 3   YEAR_y                12 non-null     float64
 4   AVGOFTSVALUE_UPDATED  12 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 576.0 bytes

In [15]:
monthly_analysis.drop(["YEAR_x","YEAR_y"],axis = 1, inplace = True)

In [16]:
import calendar
monthly_analysis['MONTH'] = monthly_analysis['MONTH'].apply(lambda x: calendar.month_abbr[x])

In [19]:
monthly_analysis.to_excel("faridpur_monthly_evaporation_analysis.xls")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  """Entry point for launching an IPython kernel.

In [20]:
monthly_analysis.nlargest(2,"MAXOFTSVALUE_UPDATED")

  MONTH  MAXOFTSVALUE_UPDATED  AVGOFTSVALUE_UPDATED
4   May              7.845455              4.298182
3   Apr              7.843478              5.095217

In [21]:
monthly_analysis.nlargest(2,"AVGOFTSVALUE_UPDATED")

  MONTH  MAXOFTSVALUE_UPDATED  AVGOFTSVALUE_UPDATED
3   Apr              7.843478              5.095217
4   May              7.845455              4.298182

In [22]:
monthly_analysis.nsmallest(2,"MAXOFTSVALUE_UPDATED")

   MONTH  MAXOFTSVALUE_UPDATED  AVGOFTSVALUE_UPDATED
0    Jan              3.720833              1.858333
11   Dec              3.827273              1.815455

In [23]:
monthly_analysis.nsmallest(2,"AVGOFTSVALUE_UPDATED")

   MONTH  MAXOFTSVALUE_UPDATED  AVGOFTSVALUE_UPDATED
11   Dec              3.827273              1.815455
0    Jan              3.720833              1.858333