In [4]:
pip install xlrd==1.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd==1.2.0 in /usr/local/lib/python3.7/dist-packages (1.2.0)

In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_excel("faridpur_ssh.xls")

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [7]:
filt = df["YEAR"] != 1987
df_new = df[filt]

In [8]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359 entries, 4 to 370
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   STATIONID             359 non-null    int64
 1   YEAR                  359 non-null    int64
 2   MONTH                 359 non-null    int64
 3   AVGOFTSVALUE_UPDATED  359 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 14.0 KB

In [9]:
monthly_avg = df_new.groupby("MONTH").mean()

In [10]:
monthly_avg = monthly_avg.reset_index()

In [11]:
import calendar
monthly_avg['MONTH'] = monthly_avg['MONTH'].apply(lambda x: calendar.month_abbr[x])

In [12]:
monthly_avg.drop(["STATIONID","YEAR"],axis = 1, inplace = True)

In [13]:
monthly_avg.to_excel("monthly_ssh_analysis_faridpur.xls")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  """Entry point for launching an IPython kernel.

In [14]:
monthly_avg.nlargest(2,"AVGOFTSVALUE_UPDATED")

  MONTH  AVGOFTSVALUE_UPDATED
3   Apr              8.005333
2   Mar              7.806333

In [15]:
monthly_avg.nsmallest(2,"AVGOFTSVALUE_UPDATED")

  MONTH  AVGOFTSVALUE_UPDATED
6   Jul              4.308333
7   Aug              4.880000